### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by silverhook** [krobelus/cyanide#4]

**Comment by silverhook** [comment]
Works with HTTP(S) fine now :+1:

But if I write an e-mail address (whether with `mailto:` or without) or an `xmpp:` address, it still tries to open it in the browser.

**Comment by krobelus** [comment]
It should now work with generic <protocol>:<address> links and also with bare email addresses
I could also add support for http links without protocol prefix (example.org) if that is deemed appropriate

**Comment by ghost** [comment]
The Messages app does that so I think it would be good to have in Cyanide as well.

**Comment by silverhook** [comment]
I agree with @plsng

**Comment by krobelus** [comment]
Should be done now... I hope me regex is not too buggy :p 
I currently prepend https: , should I use http instead?

**Comment by silverhook** [comment]
I think (sadly) some pages still don’t se https.

On the other hand, people communitcating via Tox probably use more https than plain http.
